const image = {
    add: require('../../assets/image/add.png'),
    avatar: require('../../assets/image/avatar.png'),
    addImgService: require('../../assets/image/addImgService.png'),
    addImgAdvert: require('../../assets/image/addImgAdvert.png'),
    backButton: require('../../assets/image/back.png'),
    banner: require('../../assets/image/banner.png'),
    close: require('../../assets/image/close.png'),
    email: require('../../assets/image/email.png'),
    phone: require('../../assets/image/phone.png'),
    logo: require('../../assets/image/logo.png'),
    home: require('../../assets/image/home.png'),
    profile: require('../../assets/image/profile.png'),
    feed: require('../../assets/image/feed.png'),
    favorites: require('../../assets/image/favorites.png'),
    search: require('../../assets/image/search.png'),
    iconCat: require('../../assets/image/catIcon.png'),
    iconAir: require('../../assets/image/airIcon.png'),
    iconListrik: require('../../assets/image/listrikIcon.png'),
    iconBor: require('../../assets/image/borIcon.png'),
    iconToilet: require('../../assets/image/toiletIcon.png'),
    iconRenov: require('../../assets/image/renovIcon.png'),
    iconKeramik: require('../../assets/image/keramikIcon.png'),
    iconBangunan: require('../../assets/image/bangunanIcon.png'),
    iconSearch: require('../../assets/image/searchIcon.png'),
    illusConfirmPay: require('../../assets/image/illusConfirm.png'),
    cardHome: require('../../assets/image/cardHome.png'),
    result: require('../../assets/image/result.png'),
    onBoarding1: require('../../assets/image/onBoarding1.png'),
    onBoarding2: require('../../assets/image/onBoarding2.png'),
    onBoarding3: require('../../assets/image/onBoarding3.png'),
    edit: require('../../assets/image/edit.png'),
    safety: require('../../assets/image/safety.png'),
    star: require('../../assets/image/star.png'),
    topup: require('../../assets/image/topup.png'),
    eyeActive: require('../../assets/image/eyeActive.png'),
    eyeInactive: require('../../assets/image/eyeInactive.png'),
    verifyMitra: require('../../assets/image/verifyMitra.png'),
    verifyFeed: require('../../assets/image/verifyFeed.png'),
}

export default image;